SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



CREATE TABLE IF NOT EXISTS `all_records` (
  `sno` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `isMovie` TINYINT NOT NULL,
  PRIMARY KEY (`sno`, `name`),
  UNIQUE KEY `Name_UNIQUE` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `moviesdata` (
  `sno` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `year` YEAR NULL,
  `quality` VARCHAR(10) NULL,
  `ref` VARCHAR(200) NOT NULL,
  `language` VARCHAR(45) DEFAULT NULL,
  `subtitle` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`sno`, `name`),
  UNIQUE KEY `sno_UNIQUE` (`sno`),
  UNIQUE KEY `ref_UNIQUE` (`ref`),
  UNIQUE KEY `name_quality_UNIQUE` (`name`, `quality`),
  CONSTRAINT `name_movies`
    FOREIGN KEY (`name`)
    REFERENCES `all_records` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `seriesdata` (
  `sno` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `season` VARCHAR(10) NOT NULL,
  `quality` VARCHAR(10) NULL,
  `episode` VARCHAR(20) DEFAULT 'complete',
  `ref` VARCHAR(200) NOT NULL,
  `language` VARCHAR(45) DEFAULT NULL,
  `subtitle` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`sno`, `name`),
  UNIQUE KEY `ref_UNIQUE` (`ref`),
  UNIQUE KEY `name_quality_UNIQUE` (`name`, `quality`, `season`, `episode`),
  KEY `name_idx` (`name`),
  CONSTRAINT `name_series`
    FOREIGN KEY (`name`)
    REFERENCES `all_records` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
